version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   - NODE_ENV=development
    command: npm run dev
  #   depends_on:
  #     - backend-service
  # backend-service:
  #   image: blog-api-app
  #   ports:
  #     - '8181:8181'

